set(BOOST_ROOT "C:/Users/lordjaxom/Programme/boost_1_66_0")
set(JSON_ROOT "C:/Users/lordjaxom/Programme/json-master")
set(wxWidgets_ROOT_DIR "C:/Users/lordjaxom/Programme/wxWidgets-3.1.0")
set(LIB3DPRNET_ROOT "H:/src/lib3dprnet")
set(LIB3DPRNET_BUILD_SUFFIX "-mingw")